listener 1883
allow_anonymous true
max_inflight_bytes 0
max_inflight_messages 1000
max_queued_bytes 0
max_queued_messages 10000

listener 9001
protocol websockets
allow_anonymous true

persistence true
persistence_location /mosquitto/data/
persistence_file mosquitto.db
autosave_interval 60
autosave_on_changes true

queue_qos0_messages true

connection_messages true

log_dest file /mosquitto/log/mosquitto.log
log_type error
log_type warning
log_type notice
log_type information

max_connections -1
