from typing import Dict, List, Set, Tuple
from ..models.plc_models import (
    PLCProgram,
    Rung,
    Element,
    NOContact,
    NCContact,
    Coil,
    Timer,
    Counter,
    ElementType
)


class CodeGenerator:
    def __init__(self):
        self.program: PLCProgram = None
        self.input_addresses: Set[str] = set()
        self.output_addresses: Set[str] = set()
        self.timer_addresses: Set[str] = set()
        self.counter_addresses: Set[str] = set()

    def generate(self, program: PLCProgram) -> str:
        self.program = program
        self._collect_addresses()
        
        code_lines = []
        code_lines.extend(self._generate_header())
        code_lines.append("")
        code_lines.extend(self._generate_state_class())
        code_lines.append("")
        code_lines.extend(self._generate_plc_class())
        code_lines.append("")
        code_lines.extend(self._generate_rung_methods())
        code_lines.append("")
        code_lines.extend(self._generate_cycle_method())
        code_lines.append("")
        code_lines.extend(self._generate_run_method())
        code_lines.append("")
        code_lines.extend(self._generate_main_block())
        
        return "\n".join(code_lines)

    def _collect_addresses(self):
        self.input_addresses = set(self.program.inputs.keys())
        self.output_addresses = set(self.program.outputs.keys())
        
        for rung in self.program.rungs:
            for elem in rung.elements:
                if isinstance(elem, Timer):
                    self.timer_addresses.add(elem.address)
                elif isinstance(elem, Counter):
                    self.counter_addresses.add(elem.address)

    def _generate_header(self) -> List[str]:
        return [
            '"""',
            f'PLC Program: {self.program.name}',
            f'Description: {self.program.description}',
            f'Generated by PLC Decompiler',
            '"""',
            '',
            'import time',
            'from typing import Dict, List, Any, Optional',
            'from dataclasses import dataclass, field',
            'from datetime import datetime',
        ]

    def _generate_state_class(self) -> List[str]:
        lines = [
            '@dataclass',
            'class PLCState:',
            '    inputs: Dict[str, bool] = field(default_factory=dict)',
            '    outputs: Dict[str, bool] = field(default_factory=dict)',
            '    timers: Dict[str, Dict[str, Any]] = field(default_factory=dict)',
            '    counters: Dict[str, Dict[str, Any]] = field(default_factory=dict)',
            '    internal: Dict[str, bool] = field(default_factory=dict)',
            '    execution_log: List[Dict[str, Any]] = field(default_factory=list)',
        ]
        return lines

    def _generate_plc_class(self) -> List[str]:
        lines = [
            'class PLCProgramExecutor:',
            '    def __init__(self):',
            '        self.state = PLCState()',
            '        self._initialize_state()',
            '',
            '    def _initialize_state(self):',
        ]
        
        for addr in sorted(self.input_addresses):
            lines.append(f'        self.state.inputs["{addr}"] = False')
        
        for addr in sorted(self.output_addresses):
            lines.append(f'        self.state.outputs["{addr}"] = False')
        
        for addr in sorted(self.timer_addresses):
            lines.append(f'        self.state.timers["{addr}"] = {{"accum": 0, "done": False, "enabled": False}}')
        
        for addr in sorted(self.counter_addresses):
            lines.append(f'        self.state.counters["{addr}"] = {{"accum": 0, "done": False, "last_reset": False}}')
        
        return lines

    def _generate_rung_methods(self) -> List[str]:
        lines = []
        for rung in self.program.rungs:
            lines.extend(self._generate_single_rung_method(rung))
            lines.append("")
        return lines

    def _generate_single_rung_method(self, rung: Rung) -> List[str]:
        lines = [
            f'    def _execute_rung_{rung.id}(self):',
            f'        """Rung {rung.id}: {rung.logic}"""',
        ]
        
        input_elements = []
        output_elements = []
        
        for elem in rung.elements:
            if isinstance(elem, (NOContact, NCContact)):
                input_elements.append(elem)
            else:
                output_elements.append(elem)
        
        if input_elements:
            logic_expr = self._build_logic_expression(input_elements)
            lines.append(f'        rung_result = {logic_expr}')
        else:
            lines.append('        rung_result = True')
        
        for elem in output_elements:
            if isinstance(elem, Coil):
                lines.extend(self._generate_coil_logic(elem))
            elif isinstance(elem, Timer):
                lines.extend(self._generate_timer_logic(elem))
            elif isinstance(elem, Counter):
                lines.extend(self._generate_counter_logic(elem))
        
        if not output_elements:
            lines.append('        pass')
        
        return lines

    def _build_logic_expression(self, elements: List[Element]) -> str:
        conditions = []
        for elem in elements:
            if isinstance(elem, NOContact):
                conditions.append(f'self.state.inputs.get("{elem.address}", False)')
            elif isinstance(elem, NCContact):
                conditions.append(f'not self.state.inputs.get("{elem.address}", True)')
        
        if conditions:
            return " and ".join(conditions)
        return "True"

    def _generate_coil_logic(self, coil: Coil) -> List[str]:
        addr = coil.address
        return [
            f'        self.state.outputs["{addr}"] = rung_result',
            f'        self._log_execution({coil.id}, "{coil.name}", rung_result, rung_result)',
        ]

    def _generate_timer_logic(self, timer: Timer) -> List[str]:
        addr = timer.address
        return [
            f'        timer_state = self.state.timers["{addr}"]',
            f'        if rung_result:',
            f'            if not timer_state["enabled"]:',
            f'                timer_state["enabled"] = True',
            f'                timer_state["accum"] = 0',
            f'            timer_state["accum"] += 1',
            f'            timer_state["done"] = timer_state["accum"] >= {timer.preset}',
            f'        else:',
            f'            timer_state["enabled"] = False',
            f'            timer_state["accum"] = 0',
            f'            timer_state["done"] = False',
            f'        self._log_execution({timer.id}, "{timer.name}", rung_result, timer_state["done"])',
        ]

    def _generate_counter_logic(self, counter: Counter) -> List[str]:
        addr = counter.address
        return [
            f'        counter_state = self.state.counters["{addr}"]',
            f'        if rung_result and not counter_state.get("last_state", False):',
            f'            counter_state["accum"] += 1',
            f'            counter_state["done"] = counter_state["accum"] >= {counter.preset}',
            f'        counter_state["last_state"] = rung_result',
            f'        self._log_execution({counter.id}, "{counter.name}", rung_result, counter_state["done"])',
        ]

    def _generate_cycle_method(self) -> List[str]:
        lines = [
            '    def execute_cycle(self, cycle_num: int = 0):',
            '        """Execute one full PLC scan cycle"""',
        ]
        for rung in self.program.rungs:
            lines.append(f'        self._execute_rung_{rung.id}()')
        return lines

    def _generate_run_method(self) -> List[str]:
        return [
            '    def _log_execution(self, element_id: int, element_name: str, input_val: bool, output_val: bool):',
            '        log_entry = {',
            '            "timestamp": datetime.now(),',
            '            "element_id": element_id,',
            '            "element_name": element_name,',
            '            "input_value": input_val,',
            '            "output_value": output_val',
            '        }',
            '        self.state.execution_log.append(log_entry)',
            '',
            '    def run(self, cycles: int = 10, inputs: Optional[Dict[str, bool]] = None):',
            '        """Run the PLC program for specified number of cycles"""',
            '        if inputs:',
            '            for addr, value in inputs.items():',
            '                if addr in self.state.inputs:',
            '                    self.state.inputs[addr] = value',
            '',
            '        self.state.execution_log = []',
            '',
            '        for cycle in range(cycles):',
            '            self.execute_cycle(cycle)',
            '',
            '        return {',
            '            "final_state": {',
            '                "inputs": dict(self.state.inputs),',
            '                "outputs": dict(self.state.outputs),',
            '                "timers": dict(self.state.timers),',
            '                "counters": dict(self.state.counters)',
            '            },',
            '            "execution_log": self.state.execution_log',
            '        }',
        ]

    def _generate_main_block(self) -> List[str]:
        return [
            'if __name__ == "__main__":',
            '    plc = PLCProgramExecutor()',
            '    result = plc.run(cycles=5)',
            '    print("Final Outputs:", result["final_state"]["outputs"])',
        ]
